### ISSUE TITLE
Provide license

### ISSUE THREAD

**Issue by rettinghaus** [humdrum-tools/bach-wtc#1]
It is unclear for what purposes the files could be reused.

**Comment by craigsapp** [comment]
The license for the preludes is technically: http://old.musedata.org/legal/licen.html
which translates roughly to fair use.

I don't think there was a license for the fugues, which come from another encoder, but both are based on BG.   The fugues are for analytic purposes, with voices separated (basically on separate staves).  I have split out these fugues into a separate repository:  https://github.com/humdrum-tools/bach-wtc-fugues
When I finish updating these I will check with David Huron about adding a CC license.

Then I will replace the fugues in this repository with the fugue encodings that match the preludes.

**Comment by craigsapp** [comment]
Another thought: The preludes are in a form that cannot be converted well into MEI currently.  They are encoded with one spine for the part rather than by staff.  I expect two spines (one for each staff in the grand staff) when converting from Humdrum to MEI.   I use subspines to map to MEI layers, and I do not want to complicate that system to also handle staff assignments (although I will think about it, since it will not impossible -- but rather tedious to implement and involve lots of bug fixes similar to issue https://github.com/rism-ch/verovio/issues/1792).

This would be fairly easy to fix by hand, but I am also working on a built-in converter that could convert directly from MuseData to Humdrum (and then to MEI via verovio):
     https://github.com/craigsapp/humlib/blob/master/src/tool-musedata2hum.cpp
     https://github.com/craigsapp/humlib/blob/master/src/MuseData.cpp
     https://github.com/craigsapp/humlib/blob/master/src/MuseRecord.cpp
     https://github.com/craigsapp/humlib/blob/master/src/MuseRecordBasic.cpp
I have not dealt with piano or organ music yet, but I will see if I can get to that by the end of the year.  Single staff parts are working reasonably well now, however.

**Comment by craigsapp** [comment]
Also note that the PDF files associated with the prelude digital scores are starting to come online:

http://www.musedata.org

<img width="1047" alt="Screen Shot 2020-11-01 at 1 08 12 PM" src="https://user-images.githubusercontent.com/3487289/97815503-5f2b6c80-1c43-11eb-9c82-5c1f2f5a4f99.png">

First page of book I, prelude 4:

<img width="650" alt="Screen Shot 2020-11-01 at 1 07 46 PM" src="https://user-images.githubusercontent.com/3487289/97815504-60f53000-1c43-11eb-9ef5-7b3e4bd8472a.png">
